[package]
name = "smpl-gloss-integration"
authors.workspace = true
description = "Integration between smpl-rs and gloss"
edition.workspace = true
publish = true
readme = "README.md"
rust-version.workspace = true
version.workspace = true
keywords.workspace = true
license.workspace = true
documentation = "https://docs.rs/smpl-gloss-integration"
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["with-gui", "private"]
with-gui=["dep:egui", "gloss-renderer/with-gui"]
private = ["smpl-core/private"]
burn-torch = ["tch", "wgpu-cuda-interop/cuda"]

[dependencies]
# Workspace internal
smpl-core.workspace=true
smpl-utils.workspace=true
easy-wgpu.workspace=true
gloss-hecs.workspace=true
gloss-renderer.workspace=true
gloss-utils.workspace=true
gloss-img.workspace=true
gloss-geometry.workspace=true
gloss-burn-multibackend.workspace=true
wgpu-burn-interop.workspace=true
wgpu-cuda-interop = {workspace=true, optional = true}

# Workspace third-party
egui = {workspace=true, optional = true}
log.workspace=true
cfg-if.workspace=true
nalgebra.workspace=true
ndarray.workspace=true
burn.workspace=true
wgpu.workspace=true
wasm-timer.workspace=true
image.workspace=true
bytemuck_derive.workspace=true
tch= { workspace = true, optional = true }
serde.workspace=true
num-traits.workspace=true
num-derive.workspace=true
erased-serde.workspace=true
bincode.workspace=true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
crossbeam-channel.workspace=true
abi_stable.workspace=true

#added it to get the log! macro
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys.workspace=true


[target.x86_64-unknown-linux-gnu] #slightly faster linking
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[lints]
workspace = true