[package]
name = "mcs_gltf_export"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
smpl-core = { path = "../../crates/smpl_core", default-features = false  }
smpl-gloss-integration = { path = "../../crates/smpl_gloss_integration", default-features = false  }
gloss-renderer = {workspace= true, default-features = false}

#third party
burn.workspace=true
