pub const NUM_BODY_JOINTS: usize = 21;
pub const NUM_HAND_JOINTS: usize = 15;
pub const NUM_FACE_JOINTS: usize = 3;
pub const NUM_JOINTS: usize = NUM_BODY_JOINTS + 2 * NUM_HAND_JOINTS + NUM_FACE_JOINTS; //54 joints
pub const NECK_IDX: usize = 12;
pub const NUM_VERTS: usize = 10475;
pub const NUM_VERTS_UV_MESH: usize = 11307;
pub const NUM_FACES: usize = 20908;
pub const FULL_SHAPE_SPACE_DIM: usize = 400; //contains both the shape dirs(300betas) and the expression dirs(100 expression
                                             // coeffs)
pub const SHAPE_SPACE_DIM: usize = 300;
pub const EXPRESSION_SPACE_DIM: usize = 100;
pub const NUM_POSE_BLEND_SHAPES: usize = NUM_JOINTS * 9;

// 55 joints here, since the pelvis (origin) is a joint in this respect
pub const JOINT_NAMES_UNREAL: [&str; 55] = [
    "pelvis",
    "thigh_l",
    "thigh_r",
    "spine_01",
    "calf_l",
    "calf_r",
    "spine_02",
    "foot_l",
    "foot_r",
    "spine_03",
    "ball_l",
    "ball_r",
    "neck_01",
    "clavicle_l",
    "clavicle_r",
    "head",
    "upperarm_l",
    "upperarm_r",
    "lowerarm_l",
    "lowerarm_r",
    "hand_l",
    "hand_r",
    "jaw",
    "eye_l",
    "eye_r",
    "index_01_l",
    "index_02_l",
    "index_03_l",
    "middle_01_l",
    "middle_02_l",
    "middle_03_l",
    "pinky_01_l",
    "pinky_02_l",
    "pinky_03_l",
    "ring_01_l",
    "ring_02_l",
    "ring_03_l",
    "thumb_01_l",
    "thumb_02_l",
    "thumb_03_l",
    "index_01_r",
    "index_02_r",
    "index_03_r",
    "middle_01_r",
    "middle_02_r",
    "middle_03_r",
    "pinky_01_r",
    "pinky_02_r",
    "pinky_03_r",
    "ring_01_r",
    "ring_02_r",
    "ring_03_r",
    "thumb_01_r",
    "thumb_02_r",
    "thumb_03_r",
];

// 55 joints here, since the pelvis (origin) is a joint in this respect
pub const JOINT_NAMES: [&str; 55] = [
    "pelvis",
    "left_hip",
    "right_hip",
    "spine1",
    "left_knee",
    "right_knee",
    "spine2",
    "left_ankle",
    "right_ankle",
    "spine3",
    "left_foot",
    "right_foot",
    "neck",
    "left_collar",
    "right_collar",
    "head",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "jaw",
    "left_eye_smplhf",
    "right_eye_smplhf",
    "left_index1",
    "left_index2",
    "left_index3",
    "left_middle1",
    "left_middle2",
    "left_middle3",
    "left_pinky1",
    "left_pinky2",
    "left_pinky3",
    "left_ring1",
    "left_ring2",
    "left_ring3",
    "left_thumb1",
    "left_thumb2",
    "left_thumb3",
    "right_index1",
    "right_index2",
    "right_index3",
    "right_middle1",
    "right_middle2",
    "right_middle3",
    "right_pinky1",
    "right_pinky2",
    "right_pinky3",
    "right_ring1",
    "right_ring2",
    "right_ring3",
    "right_thumb1",
    "right_thumb2",
    "right_thumb3",
];

pub const PARENT_ID_PER_JOINT: [u32; 55] = [
    4_294_967_295,
    0,
    0,
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    9,
    9,
    12,
    13,
    14,
    16,
    17,
    18,
    19,
    15,
    15,
    15,
    20,
    25,
    26,
    20,
    28,
    29,
    20,
    31,
    32,
    20,
    34,
    35,
    20,
    37,
    38,
    21,
    40,
    41,
    21,
    43,
    44,
    21,
    46,
    47,
    21,
    49,
    50,
    21,
    52,
    53,
];
