# `getrandom_backend="wasm_js"` is required to enable the `getrandom` crate to use the `wasm_js` backend.
# https://docs.rs/getrandom/latest/getrandom/#webassembly-support
[target.wasm32-unknown-unknown]
rustflags = ['--cfg=getrandom_backend="wasm_js"']